name: Build and Test
on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Backend Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Backend Tests
        run: |
          python -m unittest discover
  frontend:
      runs-on: ubuntu-latest
      steps:
        - name: Check out the code
          uses: actions/checkout@v3
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 14
        - name: Install Frontend Dependencies
          run: |
            npm install
        - name: Run Frontend Tests
          run: |
            npm test
  selenium-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up Selenium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin
          rm chromedriver_linux64.zip
          pip install selenium
      - name: Run Selenium Tests
        run: |
          python path/to/your/selenium_tests.py
